### ISSUE TITLE
The calendar can't be loaded from Home Assistant component

### ISSUE THREAD

**Issue by leloberg** [atomic7777/atomic_calendar#15]
Hi

After the latest commits I get the error message "The calendar can't be loaded from Home Assistant component" in the GUI. I've tried restarts, changing the version in the reference in ui-lovelace.yaml. 

Reverting back to older version works. 

Thanks :)

**Comment by atomic7777** [comment]
Sorry I tested it and it was working with my configurations. Any errors in the console?
I'll try to fix it as fast as I can

**Comment by leloberg** [comment]
This might be on my end, as it seems like someone got this working. The error message is from your code, but I don't get anything in the console that I've found.

**Comment by IIIdefconIII** [comment]
I had the same thing, i had to add the entity:

```
  - entities:
      - entity: calendar.xxx
      - calendar.xxx
    title: Thomas
    type: 'custom:atomic-calendar'
```
