### ISSUE TITLE
First Day of Week not working 

### ISSUE THREAD

**Issue by Sleeepy2** [atomic7777/atomic_calendar#18]
This is my config
```
defaultMode: 2
entities:
  - entity: calendar.sgmail_com
    type: icon2
firstDayOfWeek: 7
maxDaysToShow: 31
title: Sleep Home Calendar
type: 'custom:atomic-calendar'
```

The first day of the week shows as Sunday in the config however as soon as I save it it goes back to having Monday as the first day.
I am using version 0.7.4 of the calendar according to the updater, using version 0.94.3 Hass.io. 
Let me know if you need anything else.
